/*
 *  Copyright 2006, 2007 Alessandro Chiari.
 *
 *  This file is part of BrewPlus.
 *
 *  BrewPlus is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  BrewPlus is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with BrewPlus; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

package jmash;

/**
 *
 * @author  Alessandro
 */
public class EvaporationForm extends javax.swing.JInternalFrame {
    
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    
    /** Creates new form EvaporationForm */
    public EvaporationForm() {
	initComponents();
	setBorder(Utils.getDefaultBorder());
	setBackground(getBackground().darker());
	this.fldLitriIni.setModel(27,1,9999999999.99,0.5,"0.0","EvaporationForm.ini");
	this.fldLitriFin.setModel(23,1,9999999999.99,0.5,"0.0","EvaporationForm.fin");
	this.fldMinuti.setModel(60,1,9999999999.99,1,"0","EvaporationForm.min");
	this.fldEvap.setModel(4,0,9999999999.99,0.25,"0.00","EvaporationForm.ev");
	
//	this.fldKW.setModel(4,0,9999999999.99,0.25,"0.00");
//	this.fldDispersione.setModel(30,0,100,0.25,"0.00");
	calculateFin();
	calculateIni();
	
    }
    private Ricetta ricetta;
    public EvaporationForm( Ricetta ricetta,double litriIni,double litriFin, double densitaF,int minuti) {
	this();
	this.ricetta=ricetta;
	this.litriIni=litriIni;
	this.litriFin=litriFin;
	this.densitaFin=densitaF;
	fldMinuti.setDoubleValue(minuti);
	fldLitriIni.setVolume(litriIni);
	fldLitriFin.setVolume(litriFin);

	fldFG.setGravity(densitaF);
	calculateFin();
	calculateIni();
	
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fldEvap = new jmash.component.JMashSpinner();
        jLabel4 = new javax.swing.JLabel();
        fldPercentuale = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fldLitriIni = new jmash.component.JVolumeSpinner();
        jLabel6 = new javax.swing.JLabel();
        fldOG = new jmash.component.JGravitySpinner();
        jLabel5 = new javax.swing.JLabel();
        fldMinuti = new jmash.component.JMashSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        fldLitriFin = new jmash.component.JVolumeSpinner();
        jLabel16 = new javax.swing.JLabel();
        fldFG = new jmash.component.JGravitySpinner();

        setClosable(true);
        setIconifiable(true);
        setTitle("Calcoli Evaporazione");
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Situazione attrezzatura"));
        jPanel3.setPreferredSize(new java.awt.Dimension(620, 80));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Litri evaporati/ora");
        jPanel3.add(jLabel2);

        fldEvap.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fldEvapStateChanged(evt);
            }
        });
        jPanel3.add(fldEvap);

        jLabel4.setText("% evap./ora");
        jPanel3.add(jLabel4);

        fldPercentuale.setPreferredSize(new java.awt.Dimension(250, 21));
        fldPercentuale.setStringPainted(true);
        jPanel3.add(fldPercentuale);

        getContentPane().add(jPanel3);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Situazione iniziale - pre bollitura"));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 80));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Volume");
        jPanel1.add(jLabel1);

        fldLitriIni.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fldLitriIniStateChanged(evt);
            }
        });
        jPanel1.add(fldLitriIni);

        jLabel6.setText("Densità");
        jPanel1.add(jLabel6);

        fldOG.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fldOGStateChanged(evt);
            }
        });
        jPanel1.add(fldOG);

        jLabel5.setText("Minuti bollitura");
        jPanel1.add(jLabel5);

        fldMinuti.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fldMinutiStateChanged(evt);
            }
        });
        jPanel1.add(fldMinuti);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Situazione finale - post bollitura"));
        jPanel2.setPreferredSize(new java.awt.Dimension(620, 80));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel15.setText("Volume");
        jPanel2.add(jLabel15);

        fldLitriFin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fldLitriFinStateChanged(evt);
            }
        });
        jPanel2.add(fldLitriFin);

        jLabel16.setText("Densità");
        jPanel2.add(jLabel16);

        fldFG.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fldFGStateChanged(evt);
            }
        });
        jPanel2.add(fldFG);

        getContentPane().add(jPanel2);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-685)/2, (screenSize.height-296)/2, 685, 296);
    }// </editor-fold>//GEN-END:initComponents
        
    private void fldEvapStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fldEvapStateChanged
	calculateFin();
    }//GEN-LAST:event_fldEvapStateChanged
    
    private void fldMinutiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fldMinutiStateChanged
	calculateFin();
    }//GEN-LAST:event_fldMinutiStateChanged
    
    private void fldFGStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fldFGStateChanged
	calculateIni();
    }//GEN-LAST:event_fldFGStateChanged
    
    private void fldOGStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fldOGStateChanged
	calculateFin();
    }//GEN-LAST:event_fldOGStateChanged
    
    private void fldLitriFinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fldLitriFinStateChanged
	calculateIni();
    }//GEN-LAST:event_fldLitriFinStateChanged
    
    private void fldLitriIniStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fldLitriIniStateChanged
	calculateFin();
    }//GEN-LAST:event_fldLitriIniStateChanged
    private boolean flag=false;
    private double litriIni,litriFin, densitaIni, densitaFin, kw, dispersione,  evaporazione, percentuale;

    private void calculateFin(){
	if(flag)return;
	flag=true;
	litriFin=fldLitriIni.getVolume()-fldEvap.getDoubleValue()*fldMinuti.getDoubleValue()/60;
	this.densitaFin=
		Utils.Plato2SG(
		Utils.SG2Plato(fldOG.getGravity())*fldLitriIni.getVolume()/litriFin);
	
	fldFG.setGravity(this.densitaFin);
	fldLitriFin.setVolume(litriFin);
	fldPercentuale.setValue((int)(
		100*fldEvap.getDoubleValue()/fldLitriIni.getVolume())
		);	
	flag=false;
    }
    private void calculateIni(){
	if(flag)return;
	flag=true;
	fldEvap.setDoubleValue(
		(fldLitriIni.getVolume()-fldLitriFin.getVolume())*fldMinuti.getDoubleValue()/60
		);
	this.densitaIni=
		Utils.Plato2SG(
		Utils.SG2Plato(fldFG.getGravity())*fldLitriFin.getVolume()/fldLitriIni.getVolume());
	
	fldOG.setGravity(this.densitaIni);
	
	fldPercentuale.setValue((int)(
		100*fldEvap.getDoubleValue()/fldLitriIni.getVolume())
		);

	
	flag=false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jmash.component.JMashSpinner fldEvap;
    private jmash.component.JGravitySpinner fldFG;
    private jmash.component.JVolumeSpinner fldLitriFin;
    private jmash.component.JVolumeSpinner fldLitriIni;
    private jmash.component.JMashSpinner fldMinuti;
    private jmash.component.JGravitySpinner fldOG;
    private javax.swing.JProgressBar fldPercentuale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
}
