/*
 
 *
 *  This file is part of BrewPlus.
 *
 *  BrewPlus is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  BrewPlus is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with BrewPlus; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

package jmash;

import javax.swing.JInternalFrame;
import jmash.tableModel.MashLogTableModel;
import org.jdom.Element;

/**
 *
 * @author  Alessandro
 */
public class PanelMashLog extends javax.swing.JPanel {
    public MashLogTableModel mashStepTableModel;
    private Ricetta ricetta;
    private JInternalFrame parentFrame;
    
    /** Creates new form PanelMashLog */
    public PanelMashLog(Ricetta r, JInternalFrame parentFrame) {
	this.ricetta=r;
	this.parentFrame=parentFrame;	
	initComponents();
	this.mashStepTableModel=new MashLogTableModel(this);
	this.tblMashSteps.setModel(this.mashStepTableModel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMashSteps = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAdd3 = new javax.swing.JButton();
        btnRem3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout(5, 0));

        jScrollPane5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jScrollPane5.setMinimumSize(null);
        jScrollPane5.setPreferredSize(new java.awt.Dimension(150, 120));
        jScrollPane5.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane5MouseWheelMoved(evt);
            }
        });

        tblMashSteps.setPreferredSize(null);
        tblMashSteps.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tblMashStepsMouseWheelMoved(evt);
            }
        });

        jScrollPane5.setViewportView(tblMashSteps);

        jPanel5.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jPanel1.setPreferredSize(new java.awt.Dimension(36, 46));
        btnAdd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmash/images/edit_add.png")));
        btnAdd3.setToolTipText(java.util.ResourceBundle.getBundle("jmash/lang").getString("Aggiungi"));
        btnAdd3.setAlignmentX(0.5F);
        btnAdd3.setMaximumSize(new java.awt.Dimension(30, 30));
        btnAdd3.setMinimumSize(new java.awt.Dimension(30, 30));
        btnAdd3.setPreferredSize(new java.awt.Dimension(36, 36));
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });

        jPanel1.add(btnAdd3);

        btnRem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmash/images/edit_remove.png")));
        btnRem3.setToolTipText(java.util.ResourceBundle.getBundle("jmash/lang").getString("Rimuovi"));
        btnRem3.setAlignmentX(0.5F);
        btnRem3.setMaximumSize(new java.awt.Dimension(30, 30));
        btnRem3.setMinimumSize(new java.awt.Dimension(30, 30));
        btnRem3.setPreferredSize(new java.awt.Dimension(36, 36));
        btnRem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRem3ActionPerformed(evt);
            }
        });

        jPanel1.add(btnRem3);

        jPanel5.add(jPanel1, java.awt.BorderLayout.EAST);

        add(jPanel5, java.awt.BorderLayout.WEST);

    }// </editor-fold>//GEN-END:initComponents

    private void btnRem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRem3ActionPerformed
	if(!tblMashSteps.isEnabled())return;
	this.mashStepTableModel.remRow(this.tblMashSteps.getSelectedRow());
	logModificato();
    }//GEN-LAST:event_btnRem3ActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
	TLog step=new TLog();
        TLog prev=mashStepTableModel.getLastRow();
        if(prev!=null){
            step.setMinuto(prev.getMinuto()+5);
            step.setTemperatura(prev.getTemperatura()+5);
            step.setPH(prev.getPH()*0.9);
        }        
	this.mashStepTableModel.addRow(step);
	logModificato();
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void jScrollPane5MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane5MouseWheelMoved
	
    }//GEN-LAST:event_jScrollPane5MouseWheelMoved

    private void tblMashStepsMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_tblMashStepsMouseWheelMoved
	
    }//GEN-LAST:event_tblMashStepsMouseWheelMoved
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnRem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblMashSteps;
    // End of variables declaration//GEN-END:variables
    private PanelMashStep mashDesign;
    public void setMainPanel(PanelMashStep P){
	this.mashDesign=P;
	add(P, java.awt.BorderLayout.CENTER);
    }
    
    public void logModificato(){
	this.mashDesign.publicData.clear();
        this.mashDesign.publicPH.clear();
	for(TLog m: mashStepTableModel.getRows()){
	    this.mashDesign.publicData.add(m.getMinuto(), m.getTemperatura());
            this.mashDesign.publicPH.add(m.getMinuto(), m.getPH());
	}
	this.mashDesign.publicData.fireSeriesChanged();
    }
    public Element toXml(){
	Element root=new Element("mashLog");
	for(TLog m: mashStepTableModel.getRows()){
	    root.addContent(m.toXml());
	}
	return root;
    }
    public void add(TLog e) {
        mashStepTableModel.addRow(e);
    }
    public void svuota()
    {
    	mashStepTableModel.remAllRows();
    }
}
