/*
 * ViewHtml.java
 *
 * Created on 12 ottobre 2007, 12.48
 */

package jmash;

import javax.swing.JEditorPane;

/**
 *
 * @author  AChiari
 */
public class ViewHtml extends javax.swing.JInternalFrame {
    
    /** Creates new form ViewHtml */
    public ViewHtml(String str) {
        initComponents();
        setBorder(Utils.getDefaultBorder());
        
        try {

            
            
            

            JEditorPane disp = new JEditorPane("text/html", str);
            disp.setEditable(false);
            jScrollPane1.setViewportView(disp);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        TP = new javax.swing.JTextPane();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        jScrollPane1.setViewportView(TP);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-627)/2, (screenSize.height-460)/2, 627, 460);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TP;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
