/*

 *
 *  This file is part of BrewPlus.
 *
 *  BrewPlus is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  BrewPlus is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with BrewPlus; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
package jmash;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.border.TitledBorder;
import jmash.tableModel.NumberFormatter;
import org.jdom.Document;
import org.jdom.Element;

/**
 * Dati delle acque presi da http://www.unm.edu/~draper/beer/waterpro.html
 * @author  Alessandro
 */
public class WaterAdjust extends javax.swing.JInternalFrame {
    
    
    
    /**
     *
     */
    private static final long serialVersionUID = -2743109443467717746L;
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        fromPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spinCalcio = new jmash.component.JMashSpinner();
        jLabel2 = new javax.swing.JLabel();
        spinMagnesio = new jmash.component.JMashSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinSolfato = new jmash.component.JMashSpinner();
        jLabel4 = new javax.swing.JLabel();
        spinCloruro = new jmash.component.JMashSpinner();
        jLabel5 = new javax.swing.JLabel();
        spinSodio = new jmash.component.JMashSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        spinCarb = new jmash.component.JMashSpinner();
        destPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        spinCalcio1 = new jmash.component.JMashSpinner();
        jLabel7 = new javax.swing.JLabel();
        spinMagnesio1 = new jmash.component.JMashSpinner();
        jLabel8 = new javax.swing.JLabel();
        spinSolfato1 = new jmash.component.JMashSpinner();
        jLabel9 = new javax.swing.JLabel();
        spinCloruro1 = new jmash.component.JMashSpinner();
        jLabel10 = new javax.swing.JLabel();
        spinSodio1 = new jmash.component.JMashSpinner();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        spinCarb1 = new jmash.component.JMashSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        spinLitri = new jmash.component.JMashSpinner();
        txtGypsum = new javax.swing.JTextField();
        txtEpsom = new javax.swing.JTextField();
        txtCaCl2 = new javax.swing.JTextField();
        txtNaCl = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtChalk = new javax.swing.JTextField();
        txtSoda = new javax.swing.JTextField();
        useGypsum = new javax.swing.JCheckBox();
        useEpsom = new javax.swing.JCheckBox();
        useCaCl2 = new javax.swing.JCheckBox();
        useNaCl = new javax.swing.JCheckBox();
        useChalk = new javax.swing.JCheckBox();
        useSoda = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        spinCalcio2 = new jmash.component.JMashSpinner();
        jLabel16 = new javax.swing.JLabel();
        spinMagnesio2 = new jmash.component.JMashSpinner();
        jLabel17 = new javax.swing.JLabel();
        spinSolfato2 = new jmash.component.JMashSpinner();
        jLabel18 = new javax.swing.JLabel();
        spinCloruro2 = new jmash.component.JMashSpinner();
        jLabel19 = new javax.swing.JLabel();
        spinSodio2 = new jmash.component.JMashSpinner();
        jLabel30 = new javax.swing.JLabel();
        spinCarb2 = new jmash.component.JMashSpinner();
        jPanel5 = new javax.swing.JPanel();
        pCalcio = new javax.swing.JSlider();
        jLabel20 = new javax.swing.JLabel();
        pMagnesio = new javax.swing.JSlider();
        pSolfato = new javax.swing.JSlider();
        pCloruro = new javax.swing.JSlider();
        pSodio = new javax.swing.JSlider();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pCarbonato = new javax.swing.JSlider();
        jLabel31 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Water adjust");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                stopThread(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        fromPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Origine"));
        jLabel1.setText("Calcio");

        spinCalcio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinCalcioStateChanged(evt);
            }
        });

        jLabel2.setText("Magnesio");

        spinMagnesio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinMagnesioStateChanged(evt);
            }
        });

        jLabel3.setText("Solfato");

        spinSolfato.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinSolfatoStateChanged(evt);
            }
        });

        jLabel4.setText("Cloruro");

        spinCloruro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinCloruroStateChanged(evt);
            }
        });

        jLabel5.setText("Sodio");

        spinSodio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinSodioStateChanged(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmash/images/fileopen.png")));
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setMaximumSize(new java.awt.Dimension(37, 35));
        jButton1.setMinimumSize(new java.awt.Dimension(37, 35));
        jButton1.setPreferredSize(new java.awt.Dimension(37, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmash/images/filesave.png")));
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setMaximumSize(new java.awt.Dimension(37, 35));
        jButton2.setMinimumSize(new java.awt.Dimension(37, 35));
        jButton2.setPreferredSize(new java.awt.Dimension(37, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel28.setText("Carb.");

        spinCarb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinCarbStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout fromPanelLayout = new org.jdesktop.layout.GroupLayout(fromPanel);
        fromPanel.setLayout(fromPanelLayout);
        fromPanelLayout.setHorizontalGroup(
            fromPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, fromPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinCalcio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinMagnesio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinSolfato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinCloruro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinSodio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel28)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinCarb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        fromPanelLayout.setVerticalGroup(
            fromPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(fromPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel1)
                .add(spinCalcio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel2)
                .add(spinMagnesio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel3)
                .add(spinSolfato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel4)
                .add(spinCloruro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel5)
                .add(spinSodio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel28)
                .add(spinCarb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        destPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Target"));
        jLabel6.setText("Calcio");

        jLabel7.setText("Magnesio");

        jLabel8.setText("Solfato");

        jLabel9.setText("Cloruro");

        jLabel10.setText("Sodio");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmash/images/filesave.png")));
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setMaximumSize(new java.awt.Dimension(37, 35));
        jButton3.setMinimumSize(new java.awt.Dimension(37, 35));
        jButton3.setPreferredSize(new java.awt.Dimension(37, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmash/images/fileopen.png")));
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setMaximumSize(new java.awt.Dimension(37, 35));
        jButton4.setMinimumSize(new java.awt.Dimension(37, 35));
        jButton4.setPreferredSize(new java.awt.Dimension(37, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel29.setText("Carb.");

        spinCarb1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinCarb1StateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout destPanelLayout = new org.jdesktop.layout.GroupLayout(destPanel);
        destPanel.setLayout(destPanelLayout);
        destPanelLayout.setHorizontalGroup(
            destPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, destPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinCalcio1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinMagnesio1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinSolfato1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinCloruro1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinSodio1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel29)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinCarb1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        destPanelLayout.setVerticalGroup(
            destPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(destPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel6)
                .add(spinCalcio1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel7)
                .add(spinMagnesio1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel8)
                .add(spinSolfato1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel9)
                .add(spinCloruro1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel10)
                .add(spinSodio1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel29)
                .add(spinCarb1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Si ottiene tramite le seguenti aggiunte"));
        jLabel11.setText("Gypsum");

        jLabel12.setText("Epsom");

        jLabel13.setText("CaCl2");

        jLabel14.setText("NaCl");

        jLabel25.setText("litri");

        txtGypsum.setEditable(false);

        txtEpsom.setEditable(false);

        txtCaCl2.setEditable(false);

        txtNaCl.setEditable(false);

        jLabel26.setText("Chalk");

        jLabel27.setText("Soda");

        txtChalk.setEditable(false);

        txtSoda.setEditable(false);

        useGypsum.setSelected(true);
        useGypsum.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useGypsum.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useGypsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useGypsumActionPerformed(evt);
            }
        });

        useEpsom.setSelected(true);
        useEpsom.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useEpsom.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useEpsom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useEpsomActionPerformed(evt);
            }
        });

        useCaCl2.setSelected(true);
        useCaCl2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useCaCl2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useCaCl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useCaCl2ActionPerformed(evt);
            }
        });

        useNaCl.setSelected(true);
        useNaCl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useNaCl.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useNaCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useNaClActionPerformed(evt);
            }
        });

        useChalk.setSelected(true);
        useChalk.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useChalk.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useChalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useChalkActionPerformed(evt);
            }
        });

        useSoda.setSelected(true);
        useSoda.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useSoda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useSoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useSodaActionPerformed(evt);
            }
        });

        jLabel32.setText("grammi");

        jLabel33.setText("grammi");

        jLabel34.setText("grammi");

        jLabel35.setText("grammi");

        jLabel36.setText("grammi");

        jLabel37.setText("grammi");

        jLabel38.setText("Quantit\u00e0");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel12)
                    .add(jLabel11)
                    .add(jLabel13)
                    .add(jLabel14)
                    .add(jLabel26)
                    .add(jLabel27))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtSoda)
                    .add(txtChalk)
                    .add(txtNaCl)
                    .add(txtCaCl2)
                    .add(txtEpsom)
                    .add(txtGypsum, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel36)
                    .add(jLabel37)
                    .add(jLabel35)
                    .add(jLabel34)
                    .add(jLabel33)
                    .add(jLabel32))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(useGypsum)
                                    .add(useEpsom))
                                .add(useCaCl2))
                            .add(useNaCl))
                        .add(useChalk))
                    .add(useSoda))
                .addContainerGap())
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel38)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinLitri, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel25)
                .add(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(spinLitri, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel25)
                    .add(jLabel38))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(useGypsum)
                    .add(txtGypsum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel32))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(useEpsom)
                    .add(txtEpsom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel33))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(useCaCl2)
                    .add(txtCaCl2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel34))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(useNaCl)
                    .add(txtNaCl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel35))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel26)
                    .add(useChalk)
                    .add(txtChalk, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel36))
                .add(4, 4, 4)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel27)
                    .add(useSoda)
                    .add(txtSoda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel37))
                .add(37, 37, 37))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Miglior approssimazione trovata"));
        jLabel15.setText("Calcio");

        jLabel16.setText("Magnesio");

        jLabel17.setText("Solfato");

        jLabel18.setText("Cloruro");

        jLabel19.setText("Sodio");

        jLabel30.setText("Carb.");

        spinCarb2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinCarb2StateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel15)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinCalcio2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel16)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinMagnesio2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel17)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinSolfato2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel18)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinCloruro2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel19)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinSodio2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel30)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(spinCarb2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(spinCalcio2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16)
                    .add(spinMagnesio2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17)
                    .add(spinSolfato2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18)
                    .add(spinCloruro2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel19)
                    .add(spinSodio2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel30)
                    .add(spinCarb2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Priorit\u00e0 di approssimazione"));
        pCalcio.setMajorTickSpacing(10);
        pCalcio.setMinorTickSpacing(5);
        pCalcio.setSnapToTicks(true);

        jLabel20.setText("Calcio");

        pMagnesio.setMajorTickSpacing(10);
        pMagnesio.setMinorTickSpacing(5);
        pMagnesio.setSnapToTicks(true);

        pSolfato.setMajorTickSpacing(10);
        pSolfato.setMinorTickSpacing(5);
        pSolfato.setSnapToTicks(true);

        pCloruro.setMajorTickSpacing(10);
        pCloruro.setMinorTickSpacing(5);
        pCloruro.setSnapToTicks(true);

        pSodio.setMajorTickSpacing(10);
        pSodio.setMinorTickSpacing(5);
        pSodio.setSnapToTicks(true);

        jLabel21.setText("Magnesio");

        jLabel22.setText("Solfato");

        jLabel23.setText("Cloruro");

        jLabel24.setText("Sodio");

        pCarbonato.setMajorTickSpacing(10);
        pCarbonato.setMinorTickSpacing(5);
        pCarbonato.setSnapToTicks(true);

        jLabel31.setText("Carb.");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel21)
                            .add(jLabel23)
                            .add(jLabel24)
                            .add(jLabel22)
                            .add(jLabel20))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pSodio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .add(pCloruro, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .add(pSolfato, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .add(pCalcio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .add(pMagnesio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(jLabel31)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pCarbonato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 328, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pCalcio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel20))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel21)
                    .add(pMagnesio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel22)
                    .add(pSolfato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel23)
                    .add(pCloruro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel24)
                    .add(pSodio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pCarbonato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel31))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(fromPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(destPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(fromPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(destPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }//GEN-END:initComponents
    
    private void useSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useSodaActionPerformed
	flagRes=true;
    }//GEN-LAST:event_useSodaActionPerformed
    
    private void useChalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useChalkActionPerformed
	flagRes=true;
    }//GEN-LAST:event_useChalkActionPerformed
    
    private void useNaClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useNaClActionPerformed
	flagRes=true;
    }//GEN-LAST:event_useNaClActionPerformed
    
    private void useCaCl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useCaCl2ActionPerformed
	flagRes=true;
    }//GEN-LAST:event_useCaCl2ActionPerformed
    
    private void useEpsomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useEpsomActionPerformed
	flagRes=true;
    }//GEN-LAST:event_useEpsomActionPerformed
    
    private void useGypsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useGypsumActionPerformed
	flagRes=true;
    }//GEN-LAST:event_useGypsumActionPerformed
    
    private void spinCarb2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinCarb2StateChanged

    }//GEN-LAST:event_spinCarb2StateChanged
    
    private void spinCarb1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinCarb1StateChanged

    }//GEN-LAST:event_spinCarb1StateChanged
    
    private void spinCarbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinCarbStateChanged
	flagRes=true;
    }//GEN-LAST:event_spinCarbStateChanged
    
    private void spinSodioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinSodioStateChanged
	flagRes=true;
    }//GEN-LAST:event_spinSodioStateChanged
    
    private void spinCloruroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinCloruroStateChanged
	flagRes=true;
    }//GEN-LAST:event_spinCloruroStateChanged
    
    private void spinSolfatoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinSolfatoStateChanged
	flagRes=true;
    }//GEN-LAST:event_spinSolfatoStateChanged
    
    private void spinMagnesioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinMagnesioStateChanged
	flagRes=true;
    }//GEN-LAST:event_spinMagnesioStateChanged
    
    private void spinCalcioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinCalcioStateChanged
	flagRes=true;
    }//GEN-LAST:event_spinCalcioStateChanged
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
	loadDest();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	saveDest();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	loadFrom();
	res=null;
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	saveFrom();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void loadFrom(){
	File file=Utils.pickFileToLoad(this, Main.waterDir);
	if(file==null)return;
	Document doc=Utils.readFileAsXml(file.toString());
	if(doc==null) {
	    return;
	}
	((TitledBorder)fromPanel.getBorder()).setTitle("Origine - "+file.getName());
	Element root=doc.getRootElement();
	WaterProfile profile=WaterProfile.fromXml(root);
	spinCalcio.setIntegerValue((int)profile.getCalcio().doubleValue());
	spinSodio.setIntegerValue((int)profile.getSodio().doubleValue());
	spinSolfato.setIntegerValue((int)profile.getSolfato().doubleValue());
	spinMagnesio.setIntegerValue((int)profile.getMagnesio().doubleValue());
	spinCloruro.setIntegerValue((int)profile.getCloruro().doubleValue());
	spinCarb.setIntegerValue((int)profile.getCarbonato().doubleValue());
	res=null;
	flagRes=true;
    }
    
    private boolean flagRes=false;
    public void saveFrom(){
	
	File file=Utils.pickFileToSave(this, Main.waterDir);
	if(file==null) {
	    return;
	}
	
	WaterProfile source = new WaterProfile(
		spinCalcio.getIntegerValue(),
		spinMagnesio.getIntegerValue(),
		spinSolfato.getIntegerValue(),
		spinCloruro.getIntegerValue(),
		spinSodio.getIntegerValue(),
		spinCarb.getIntegerValue()
		);
	Document doc=new Document();
	Element root=source.toXml();
	doc.setRootElement(root);
	Utils.saveXmlAsFile(doc, file, this);
    }
    
    private File destFile=null;
    private void loadDest(){
	File file=Utils.pickFileToLoad(this, Main.waterDir);
	if(file==null)return;
	Document doc=Utils.readFileAsXml(file.toString());
	if(doc==null) {
	    return;
	}
	((TitledBorder)destPanel.getBorder()).setTitle("Target - "+file.getName());
	Element root=doc.getRootElement();
	WaterProfile profile=WaterProfile.fromXml(root);
	spinCalcio1.setIntegerValue((int)profile.getCalcio().doubleValue());
	spinSodio1.setIntegerValue((int)profile.getSodio().doubleValue());
	spinSolfato1.setIntegerValue((int)profile.getSolfato().doubleValue());
	spinMagnesio1.setIntegerValue((int)profile.getMagnesio().doubleValue());
	spinCloruro1.setIntegerValue((int)profile.getCloruro().doubleValue());
	spinCarb1.setIntegerValue((int)profile.getCarbonato().doubleValue());
    }
    public void saveDest(){
	
	File file=Utils.pickFileToSave(this, Main.waterDir);
	if(file==null) {
	    return;
	}
	
	WaterProfile source = new WaterProfile(
		spinCalcio1.getIntegerValue(),
		spinMagnesio1.getIntegerValue(),
		spinSolfato1.getIntegerValue(),
		spinCloruro1.getIntegerValue(),
		spinSodio1.getIntegerValue(),
		spinCarb1.getIntegerValue()
		);
	Document doc=new Document();
	Element root=source.toXml();
	doc.setRootElement(root);
	Utils.saveXmlAsFile(doc, file, this);
    }
    private void stopThread(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_stopThread
	end();
    }//GEN-LAST:event_stopThread
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel destPanel;
    private javax.swing.JPanel fromPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSlider pCalcio;
    private javax.swing.JSlider pCarbonato;
    private javax.swing.JSlider pCloruro;
    private javax.swing.JSlider pMagnesio;
    private javax.swing.JSlider pSodio;
    private javax.swing.JSlider pSolfato;
    private jmash.component.JMashSpinner spinCalcio;
    private jmash.component.JMashSpinner spinCalcio1;
    private jmash.component.JMashSpinner spinCalcio2;
    private jmash.component.JMashSpinner spinCarb;
    private jmash.component.JMashSpinner spinCarb1;
    private jmash.component.JMashSpinner spinCarb2;
    private jmash.component.JMashSpinner spinCloruro;
    private jmash.component.JMashSpinner spinCloruro1;
    private jmash.component.JMashSpinner spinCloruro2;
    private jmash.component.JMashSpinner spinLitri;
    private jmash.component.JMashSpinner spinMagnesio;
    private jmash.component.JMashSpinner spinMagnesio1;
    private jmash.component.JMashSpinner spinMagnesio2;
    private jmash.component.JMashSpinner spinSodio;
    private jmash.component.JMashSpinner spinSodio1;
    private jmash.component.JMashSpinner spinSodio2;
    private jmash.component.JMashSpinner spinSolfato;
    private jmash.component.JMashSpinner spinSolfato1;
    private jmash.component.JMashSpinner spinSolfato2;
    private javax.swing.JTextField txtCaCl2;
    private javax.swing.JTextField txtChalk;
    private javax.swing.JTextField txtEpsom;
    private javax.swing.JTextField txtGypsum;
    private javax.swing.JTextField txtNaCl;
    private javax.swing.JTextField txtSoda;
    private javax.swing.JCheckBox useCaCl2;
    private javax.swing.JCheckBox useChalk;
    private javax.swing.JCheckBox useEpsom;
    private javax.swing.JCheckBox useGypsum;
    private javax.swing.JCheckBox useNaCl;
    private javax.swing.JCheckBox useSoda;
    // End of variables declaration//GEN-END:variables
    
    private boolean flag=true;
    public void end(){flag=false;}
    private WaterProfile res=null;
    private Thread thread;
    /** Creates new form WaterAdjust */
    public WaterAdjust() {
	
	
	initComponents();
	setBorder(Utils.getDefaultBorder());
	spinCalcio.setModel(10,0,1000,1);
	spinCloruro.setModel(10,0,1000,1);
	spinMagnesio.setModel(10,0,1000,1);
	spinSodio.setModel(10,0,1000,1);
	spinSolfato.setModel(10,0,1000,1);
	spinCarb.setModel(10,0,1000,1);
	spinCarb1.setModel(10,0,1000,1);
	spinCarb2.setModel(10,0,1000,1);
	spinCalcio1.setModel(10,0,1000,1);
	spinCloruro1.setModel(10,0,1000,1);
	spinMagnesio1.setModel(10,0,1000,1);
	spinSodio1.setModel(10,0,1000,1);
	spinSolfato1.setModel(10,0,1000,1);
	spinCalcio2.setModel(10,0,1000,1);
	spinCloruro2.setModel(10,0,1000,1);
	spinMagnesio2.setModel(10,0,1000,1);
	spinSodio2.setModel(10,0,1000,1);
	spinSolfato2.setModel(10,0,1000,1);
	spinLitri.setModel(40,1,999999,1);
	thread=new Thread(){
	    public void run(){
		List<WaterProfile> L=new ArrayList<WaterProfile>();
		while(flag){
		    WaterProfile source = new WaterProfile(
			    spinCalcio.getIntegerValue(),
			    spinMagnesio.getIntegerValue(),
			    spinSolfato.getIntegerValue(),
			    spinCloruro.getIntegerValue(),
			    spinSodio.getIntegerValue(),
			    spinCarb.getIntegerValue()
			    );
		    if(flagRes){flagRes=false;res=null;L.clear();}
		    if(res!=null)source=res;
		    WaterProfile dest = new WaterProfile(
			    spinCalcio1.getIntegerValue(),
			    spinMagnesio1.getIntegerValue(),
			    spinSolfato1.getIntegerValue(),
			    spinCloruro1.getIntegerValue(),
			    spinSodio1.getIntegerValue(),
			    spinCarb1.getIntegerValue()
			    );
		    int LITRI = spinLitri.getIntegerValue();
		    
		    source.setPCalcio(pCalcio.getValue());
		    source.setPSolfato(pSolfato.getValue());
		    source.setPSodio(pSodio.getValue());
		    source.setPCloruro(pCloruro.getValue());
		    source.setPMagnesio(pMagnesio.getValue());
		    source.setPCarbonato(pCarbonato.getValue());
		    
		    source.setUseGypsum(useGypsum.isSelected());
		    source.setUseEpsom(useEpsom.isSelected());
		    source.setUseSale(useNaCl.isSelected());
		    source.setUseCalciumChloride(useCaCl2.isSelected());
		    source.setUseChalk(useChalk.isSelected());
		    source.setUseSoda(useSoda.isSelected());
		    
		    res=source.target(dest,LITRI,"",100, L,100);
		    
		    txtGypsum.setText(""+NumberFormatter.format01(res.getGypsum()*Utils.litToGal(LITRI)/1000));
		    txtEpsom.setText( ""+NumberFormatter.format01(res.getEpsom()*Utils.litToGal(LITRI)/1000));
		    txtNaCl.setText(  ""+NumberFormatter.format01(res.getSale()*Utils.litToGal(LITRI)/1000));
		    txtCaCl2.setText( ""+NumberFormatter.format01(res.getCalciumChloride()*Utils.litToGal(LITRI)/1000));
		    txtChalk.setText( ""+NumberFormatter.format01(res.getChalk()*Utils.litToGal(LITRI)/1000));
		    txtSoda.setText( ""+NumberFormatter.format01(res.getSoda()*Utils.litToGal(LITRI)/1000));
		    
		    
		    spinCalcio2.setIntegerValue((int)res.getCalcioTotale());
		    spinMagnesio2.setIntegerValue((int)res.getMagnesioTotale());
		    spinSolfato2.setIntegerValue((int)res.getSolfatoTotale());
		    spinCloruro2.setIntegerValue((int)res.getCloruroTotale());
		    spinSodio2.setIntegerValue((int)res.getSodioTotale());
		    spinCarb2.setIntegerValue((int)res.getCarbonatoTotale());
		    try {
			sleep(500);
		    } catch (InterruptedException ex) {
			ex.printStackTrace();
		    }
		}
	    }
	};
	thread.start();
    }
}
