/*
 * WaterDesign.java
 *
 * Created on 28 settembre 2007, 18.53
 */

package jmash;

/**
 *
 * @author  Alessandro
 */
public class WaterDesign extends javax.swing.JInternalFrame {
    
    /** Creates new form WaterDesign */
    public WaterDesign() {
	//getContentPane().add(new WaterAdjustPanel(this), java.awt.BorderLayout.CENTER);
	initComponents();
        getContentPane().add(new WaterAdjustPanel(this));
	setBorder(Utils.getDefaultBorder());
	
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setTitle("Water Design");
        setPreferredSize(new java.awt.Dimension(700, 450));
        setVisible(true);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-958)/2, (screenSize.height-513)/2, 958, 513);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
